name: Building boringtun for armhf
run-name: ${{ github.actor }} is building boringtun for armhf debian
on:
  push:
    tags:
      - '*'
permissions:
  contents: write

jobs:
  build-for-armhf:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Preparing chroot
        id: preparing-chroot
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y mmdebstrap systemd-container debian-archive-keyring
          sudo mmdebstrap --arch=armhf --include sudo,curl,build-essential,devscripts,git bookworm /var/lib/machines/armhf-debian
          echo "Container successfully created"
      - name: Preparing repository
        uses: actions/checkout@v4
      - name: Building boringtun
        id: building_boringtun
        run: |
          cp -v ${{ github.workspace }}/prepare-chroot.sh /tmp/
          cp -v ${{ github.workspace }}/build.sh /tmp/
          sudo systemd-nspawn --bind /tmp:/tmp/hosttmp --bind-ro /etc/resolv.conf --hostname localhost --machine armhf-debian -- sh /tmp/hosttmp/prepare-chroot.sh
          sudo systemd-nspawn --bind /tmp:/tmp/hosttmp --bind-ro /etc/resolv.conf --hostname localhost --machine armhf-debian --user builder -- sh /tmp/hosttmp/build.sh
      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: /tmp/boringtun_deb/
      - name: Creating release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            /tmp/boringtun_deb/*

